{
	"about": "https://jvndb.jvn.jp/ja/contents/2017/JVNDB-2017-014013.html",
	"title": "PyYAML における信頼できないデータのデシリアライゼーションに関する脆弱性",
	"link": "https://jvndb.jvn.jp/ja/contents/2017/JVNDB-2017-014013.html",
	"description": "PyYAML には、信頼できないデータのデシリアライゼーションに関する脆弱性が存在します。\r\n",
	"identifier": "JVNDB-2017-014013",
	"references": [
		{
			"text": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-18342",
			"source": "CVE",
			"id": "CVE-2017-18342"
		},
		{
			"text": "https://nvd.nist.gov/vuln/detail/CVE-2017-18342",
			"source": "NVD",
			"id": "CVE-2017-18342"
		},
		{
			"text": "https://cwe.mitre.org/data/definitions/502.html",
			"id": "CWE-502",
			"title": "信頼できないデータのデシリアライゼーション(CWE-502)"
		}
	],
	"cpe": [
		{
			"text": "cpe:/a:pyyaml_project:pyyaml",
			"version": "2.2",
			"vendor": "The YAML Project",
			"product": "PyYAML"
		}
	],
	"cvss": [
		{
			"version": "2.0",
			"score": "7.5",
			"type": "Base",
			"severity": "High",
			"vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P"
		},
		{
			"version": "3.0",
			"score": "9.8",
			"type": "Base",
			"severity": "Critical",
			"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
		}
	],
	"date": "2018-09-04T11:58+09:00",
	"issued": "2018-09-04T11:58+09:00",
	"modified": "2018-09-04T11:58+09:00"
}
