{
  "about": "https://jvndb.jvn.jp/ja/contents/2020/JVNDB-2020-001439.html",
  "title": "PySAML2 におけるデジタル署名の検証に関する脆弱性",
  "link": "https://jvndb.jvn.jp/ja/contents/2020/JVNDB-2020-001439.html",
  "description": "PySAML2 には、デジタル署名の検証に関する脆弱性が存在します。",
  "identifier": "JVNDB-2020-001439",
  "references": [
    {
      "text": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-5390",
      "source": "CVE",
      "id": "CVE-2020-5390"
    },
    {
      "text": "https://nvd.nist.gov/vuln/detail/CVE-2020-5390",
      "source": "NVD",
      "id": "CVE-2020-5390"
    },
    {
      "text": "https://cwe.mitre.org/data/definitions/347.html",
      "id": "CWE-347",
      "title": "デジタル署名の不適切な検証(CWE-347)"
    }
  ],
  "cpe": [
    {
      "text": "cpe:/a:pysaml2_project:pysaml2",
      "version": "2.2",
      "vendor": "PySAML2 project",
      "product": "PySAML2"
    }
  ],
  "cvss": [
    {
      "version": "2.0",
      "score": "5.0",
      "type": "Base",
      "severity": "Medium",
      "vector": "AV:N/AC:L/Au:N/C:N/I:P/A:N"
    },
    {
      "version": "3.0",
      "score": "7.5",
      "type": "Base",
      "severity": "High",
      "vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N"
    }
  ],
  "date": "2020-02-06T17:39+09:00",
  "issued": "2020-02-06T17:39+09:00",
  "modified": "2020-02-06T17:39+09:00"
}
