{
  "about": "https://jvndb.jvn.jp/ja/contents/2020/JVNDB-2020-016281.html",
  "title": "Leptonica における境界外読み取りに関する脆弱性",
  "link": "https://jvndb.jvn.jp/ja/contents/2020/JVNDB-2020-016281.html",
  "description": "Leptonica には、境界外読み取りに関する脆弱性が存在します。\r\n",
  "identifier": "JVNDB-2020-016281",
  "references": [
    {
      "text": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36280",
      "source": "CVE",
      "id": "CVE-2020-36280"
    },
    {
      "text": "https://nvd.nist.gov/vuln/detail/CVE-2020-36280",
      "source": "NVD",
      "id": "CVE-2020-36280"
    },
    {
      "text": "https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=23654",
      "source": "関連文書",
      "id": "Issue 23654"
    },
    {
      "text": "https://cwe.mitre.org/data/definitions/125.html",
      "id": "CWE-125",
      "title": "境界外読み取り(CWE-125)"
    }
  ],
  "cpe": [
    {
      "text": "cpe:/a:leptonica:leptonica",
      "version": "2.2",
      "vendor": "Leptonica",
      "product": "Leptonica"
    },
    {
      "text": "cpe:/o:fedoraproject:fedora",
      "version": "2.2",
      "vendor": "Fedora Project",
      "product": "Fedora"
    }
  ],
  "cvss": [
    {
      "version": "2.0",
      "score": "5.0",
      "type": "Base",
      "severity": "Medium",
      "vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P"
    },
    {
      "version": "3.0",
      "score": "7.5",
      "type": "Base",
      "severity": "High",
      "vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  ],
  "date": "2021-11-19T16:20+09:00",
  "issued": "2021-11-19T16:20+09:00",
  "modified": "2021-11-19T16:20+09:00"
}
