{
  "about": "https://jvndb.jvn.jp/ja/contents/2020/JVNDB-2020-011800.html",
  "title": "Xen における例外的な状態の処理に関する脆弱性",
  "link": "https://jvndb.jvn.jp/ja/contents/2020/JVNDB-2020-011800.html",
  "description": "Xen には、例外的な状態の処理に関する脆弱性が存在します。\r\n",
  "identifier": "JVNDB-2020-011800",
  "references": [
    {
      "text": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-25602",
      "source": "CVE",
      "id": "CVE-2020-25602"
    },
    {
      "text": "https://nvd.nist.gov/vuln/detail/CVE-2020-25602",
      "source": "NVD",
      "id": "CVE-2020-25602"
    },
    {
      "text": "https://cwe.mitre.org/data/definitions/755.html",
      "id": "CWE-755",
      "title": "例外的な状態における不適切な処理(CWE-755)"
    }
  ],
  "cpe": [
    {
      "text": "cpe:/o:xen:xen",
      "version": "2.2",
      "vendor": "Xen プロジェクト",
      "product": "Xen"
    }
  ],
  "cvss": [
    {
      "version": "2.0",
      "score": "4.6",
      "type": "Base",
      "severity": "Medium",
      "vector": "AV:L/AC:L/Au:S/C:N/I:N/A:C"
    },
    {
      "version": "3.0",
      "score": "6.0",
      "type": "Base",
      "severity": "Medium",
      "vector": "CVSS:3.0/AV:L/AC:L/PR:H/UI:N/S:C/C:N/I:N/A:H"
    }
  ],
  "date": "2021-04-15T14:09+09:00",
  "issued": "2021-04-15T14:09+09:00",
  "modified": "2021-04-15T14:09+09:00"
}
